In [1]:
import pandas as pd
import math
import numpy as np
import ipywidgets 
import bqplot
from datetime import datetime as dt

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/UIUC-iSchool-DataViz/is445_bcubcg_fall2022/main/data/licenses_fall2022.csv')
df

,_id,License Type,Description,License Number,License Status,Business,Title,First Name,Middle,Last Name,...,Specialty/Qualifier,Controlled Substance Schedule,Delegated Controlled Substance Schedule,Ever Disciplined,LastModifiedDate,Case Number,Action,Discipline Start Date,Discipline End Date,Discipline Reason
0,1189509,DETECTIVE BOARD,PERMANENT EMPLOYEE REGISTRATION,129446286,NOT RENEWED,N,NaN,EILEEN,NaN,SANTACRUZ,...,None,None,None,N,03/18/2022,None,None,None,None,None
1,801037,DETECTIVE BOARD,FIREARM CONTROL CARD,229030294.0,NOT RENEWED,N,NaN,DAGMAR,J,NORDLUND,...,None,None,None,N,08/16/2006,None,None,None,None,None
2,365129,COSMO,LICENSED COSMETOLOGIST,11053076.0,NOT RENEWED,N,NaN,RADOJE,NaN,ZELENOVIC,...,None,None,None,N,05/26/2006,None,None,None,None,None
3,595427,COSMO,LICENSED COSMETOLOGIST,11295645.0,ACTIVE,N,NaN,BECKY SUE,L,BURROUGHS,...,None,None,None,N,11/12/2021,None,None,None,None,None
4,653668,COSMO,LICENSED NAIL TECHNICIAN,169006247,NOT RENEWED,N,NaN,BILL G,L,LETNER,...,None,None,None,N,05/30/2006,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,888281,DETECTIVE BOARD,PERMANENT EMPLOYEE REGISTRATION,129002843.0,NOT RENEWED,N,NaN,JENNIFER,NaN,DARROW,...,None,None,None,N,08/03/2006,None,None,None,None,None
9996,766623,DETECTIVE BOARD,FIREARM CONTROL CARD,229014180,TERMINATED CARD RETURNED,N,NaN,BRYAN,NaN,WILLIAMS,...,None,None,None,N,08/07/2006,None,None,None,None,None
9997,399398,COSMO,LICENSED COSMETOLOGIST,11120249,NOT RENEWED,N,NaN,EUGENE,NaN,HENDERSON JR,...,None,None,None,N,05/26/2006,None,None,None,None,None
9998,486713,COSMO,LICENSED COSMETOLOGIST,11193270,ACTIVE,N,NaN,MAHLON DOUGLAS,NaN,CLIFT,...,None,None,None,N,12/17/2021,None,None,None,None,None
9999,744770,DENTAL,REGISTERED DENTAL HYGIENIST,020012709,ACTIVE,N,NaN,KAREEM,L,HARRIS,...,None,None,None,N,10/25/2021,None,None,None,None,None

In [3]:
df = df.fillna(0)
df = pd.read_csv('https://raw.githubusercontent.com/UIUC-iSchool-DataViz/is445_bcubcg_fall2022/main/data/licenses_fall2022.csv', na_values = ['None'])
df

,_id,License Type,Description,License Number,License Status,Business,Title,First Name,Middle,Last Name,...,Specialty/Qualifier,Controlled Substance Schedule,Delegated Controlled Substance Schedule,Ever Disciplined,LastModifiedDate,Case Number,Action,Discipline Start Date,Discipline End Date,Discipline Reason
0,1189509,DETECTIVE BOARD,PERMANENT EMPLOYEE REGISTRATION,129446286,NOT RENEWED,N,NaN,EILEEN,NaN,SANTACRUZ,...,NaN,NaN,NaN,N,03/18/2022,NaN,NaN,NaN,NaN,NaN
1,801037,DETECTIVE BOARD,FIREARM CONTROL CARD,229030294.0,NOT RENEWED,N,NaN,DAGMAR,J,NORDLUND,...,NaN,NaN,NaN,N,08/16/2006,NaN,NaN,NaN,NaN,NaN
2,365129,COSMO,LICENSED COSMETOLOGIST,11053076.0,NOT RENEWED,N,NaN,RADOJE,NaN,ZELENOVIC,...,NaN,NaN,NaN,N,05/26/2006,NaN,NaN,NaN,NaN,NaN
3,595427,COSMO,LICENSED COSMETOLOGIST,11295645.0,ACTIVE,N,NaN,BECKY SUE,L,BURROUGHS,...,NaN,NaN,NaN,N,11/12/2021,NaN,NaN,NaN,NaN,NaN
4,653668,COSMO,LICENSED NAIL TECHNICIAN,169006247,NOT RENEWED,N,NaN,BILL G,L,LETNER,...,NaN,NaN,NaN,N,05/30/2006,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,888281,DETECTIVE BOARD,PERMANENT EMPLOYEE REGISTRATION,129002843.0,NOT RENEWED,N,NaN,JENNIFER,NaN,DARROW,...,NaN,NaN,NaN,N,08/03/2006,NaN,NaN,NaN,NaN,NaN
9996,766623,DETECTIVE BOARD,FIREARM CONTROL CARD,229014180,TERMINATED CARD RETURNED,N,NaN,BRYAN,NaN,WILLIAMS,...,NaN,NaN,NaN,N,08/07/2006,NaN,NaN,NaN,NaN,NaN
9997,399398,COSMO,LICENSED COSMETOLOGIST,11120249,NOT RENEWED,N,NaN,EUGENE,NaN,HENDERSON JR,...,NaN,NaN,NaN,N,05/26/2006,NaN,NaN,NaN,NaN,NaN
9998,486713,COSMO,LICENSED COSMETOLOGIST,11193270,ACTIVE,N,NaN,MAHLON DOUGLAS,NaN,CLIFT,...,NaN,NaN,NaN,N,12/17/2021,NaN,NaN,NaN,NaN,NaN
9999,744770,DENTAL,REGISTERED DENTAL HYGIENIST,020012709,ACTIVE,N,NaN,KAREEM,L,HARRIS,...,NaN,NaN,NaN,N,10/25/2021,NaN,NaN,NaN,NaN,NaN

In [6]:
df['Original Issue Date'] = pd.to_datetime(df['Original Issue Date'],errors='coerce',format='%m/%d/%Y')
df['Original Issue Year'] = df['Original Issue Date'].dt.year

df['Expiration Date'] = pd.to_datetime(df['Expiration Date'],errors='coerce',format='%m/%d/%Y')
df['Expiration Year'] = df['Expiration Date'].dt.year


df['Difference_Days'] = df['Expiration Date'] - df['Original Issue Date']
df['Difference_Days'] = df['Difference_Days'].dt.days
df['Difference_Days']

0         605.0
1        3249.0
2       14093.0
3        4330.0
4        2668.0
         ...
9995     3588.0
9996      385.0
9997        NaN
9998    14606.0
9999     5828.0
Name: Difference_Days, Length: 10000, dtype: float64

In [7]:
table = pd.pivot_table(df, values= 'Difference_Days', index= 'County' , columns= 'License Type' ,
                      aggfunc=np.mean, fill_value = 0)
table

License Type,APPRAISAL,ARCHITECT,ATHLETIC TRAINER,ATHLETICS,AUCTIONEER,CEMETERY OVERSIGHT,CLIN PSYCHOLOGIST,COLLECTION AGENCY,COMM ASSOC MGR,COSMO,...,HME AND SERVICES PROV,HOME INSPECTOR,IDPR,INTERIOR DESIGN,LAND SURVEYOR BOARD,LANDSCAPE ARCHITECT,LIMITED LIABILITY CO,MAR AND FAM THERAPIST,MASSAGE LICENSING BD,MEDICAL BOARD
County,,,,,,,,,,,,,,,,,,,,,
ADAMS,0.0,0.0,0.0,0.0,0,0,0.0,0.0,0.0,4026.363636,...,0.0,0.0,0.0,0.0,0,0,0.000000,0.0,1392.0,0
ALABAMA,0.0,0.0,0.0,0.0,0,0,0.0,0.0,0.0,454.500000,...,0.0,0.0,0.0,0.0,0,0,0.000000,0.0,0.0,0
ALEXANDER,0.0,0.0,0.0,0.0,0,0,0.0,0.0,0.0,1066.000000,...,0.0,0.0,0.0,0.0,0,0,0.000000,0.0,0.0,0
ARIZONA,0.0,0.0,0.0,0.0,0,0,0.0,0.0,0.0,643.692308,...,0.0,0.0,0.0,2962.0,0,0,0.000000,0.0,0.0,0
ARKANSAS,0.0,0.0,0.0,0.0,0,0,0.0,0.0,0.0,2858.500000,...,0.0,0.0,0.0,0.0,0,0,0.000000,0.0,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
WILLIAMSON,0.0,0.0,0.0,0.0,0,0,0.0,0.0,0.0,3386.882353,...,7892.0,0.0,0.0,0.0,0,0,0.000000,0.0,0.0,0
WINNEBAGO,0.0,0.0,0.0,0.0,0,0,0.0,1051.0,0.0,4585.777778,...,0.0,4774.0,865.0,0.0,0,0,2228.666667,709.0,0.0,0
WISCONSIN,0.0,0.0,0.0,0.0,0,0,0.0,0.0,0.0,2731.166667,...,882.0,3375.0,0.0,9882.0,5083,2540,0.000000,0.0,0.0,0
WOODFORD,0.0,0.0,0.0,0.0,0,0,0.0,0.0,0.0,5271.384615,...,0.0,0.0,0.0,0.0,0,0,0.000000,0.0,0.0,0
WYOMING,0.0,0.0,0.0,0.0,0,0,0.0,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0,0,0.000000,0.0,0.0,0

In [13]:
# (I) For the heatmap
# add scales - colors, x & y
col_sc = bqplot.ColorScale(scheme="RdPu")
x_sc = bqplot.OrdinalScale()
y_sc = bqplot.OrdinalScale()

# create axis - for colors, x & y
c_ax = bqplot.ColorAxis(scale = col_sc, 
                        orientation = 'vertical', 
                        side = 'right')
x_ax = bqplot.Axis(scale = x_sc, label='License Type Alphabetized (Numbered 1 - 26)')
y_ax = bqplot.Axis(scale = y_sc, 
                   orientation = 'vertical', 
                   label = 'County Alphabetized and Numbered')

heat_map = bqplot.GridHeatMap(color = table,
                              scales = {'color': col_sc,
                                        'row': y_sc,
                                        'column': x_sc},
                              interactions = {'click': 'select'},
                              anchor_style = {'fill':'blue'}, 
                              selected_style = {'opacity': 1.0},
                              unselected_style = {'opacity': 1.0})

fig = bqplot.Figure(marks = [heat_map], axes = [c_ax, y_ax, x_ax])
fig

Figure(axes=[ColorAxis(orientation='vertical', scale=ColorScale(scheme='RdPu'), side='right'), Axis(label='Cou…

In [14]:
table1 = pd.pivot_table(df, values= 'Difference_Days_median', index= 'Original Issue Year' , columns= 'Expiration Year', 
                      aggfunc=np.median, fill_value = 0)
table1

Expiration Year,1967.0,1977.0,1979.0,1980.0,1981.0,1982.0,1983.0,1984.0,1985.0,1986.0,...,2017.0,2018.0,2019.0,2020.0,2021.0,2022.0,2023.0,2024.0,2025.0,2099.0
Original Issue Year,,,,,,,,,,,,,,,,,,,,,
1926.0,0,0.0,0,0.0,0.0,0.0,0.0,21181,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1928.0,0,0.0,0,0.0,0.0,0.0,0.0,0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1929.0,0,0.0,0,0.0,0.0,0.0,0.0,0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1930.0,0,0.0,0,0.0,0.0,0.0,0.0,0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1933.0,0,0.0,0,0.0,0.0,0.0,18502.5,18666,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2018.0,0,0.0,0,0.0,0.0,0.0,0.0,0,0.0,0.0,...,0.0,148.0,420.5,974.0,1170.0,1431.0,1870.0,2174.0,2310.0,0.0
2019.0,0,0.0,0,0.0,0.0,0.0,0.0,0,0.0,0.0,...,0.0,0.0,187.5,619.0,833.0,1096.0,1513.0,1858.0,1871.0,0.0
2020.0,0,0.0,0,0.0,0.0,0.0,0.0,0,0.0,0.0,...,0.0,0.0,0.0,102.0,504.0,785.5,1095.0,1423.0,0.0,0.0
2021.0,0,0.0,0,0.0,0.0,0.0,0.0,0,0.0,0.0,...,0.0,0.0,0.0,0.0,234.5,498.0,778.5,1064.5,1119.5,0.0
2022.0,0,0.0,0,0.0,0.0,0.0,0.0,0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,254.0,557.0,809.0,1096.0,0.0

In [24]:
# (II) Bar plot
# scales & ax in usual way
x_scl = bqplot.OrdinalScale() # note we are back to linears
y_scl = bqplot.OrdinalScale()
ax_xcl = bqplot.Axis(label='Year', scale=x_scl)
ax_ycl = bqplot.Axis(label='Median days', scale=y_scl, 
                    orientation='vertical', side='left')
# for the lineplot of duration in a region as a function of year
# lets start with a default region & year
i,j = 0,0
ey = [df['Expiration Year'][i], df['Expiration Year'][i+1]]
oiy = [df['Original Issue Year'][j],df['Original Issue Year'][j+1]]
region_mask = ( (df['Original Issue Year'] >= oiy[0]) & (df['Original Issue Year']<=oiy[1]) &\
                (df['Expiration Year'] >= ey[0]) & (df['Expiration Year']<=ey[1]) )

# we can see this selects for the upper right point of our heatmap
oiy, ey, df['Original Issue Year'][region_mask]

# lets plot the durations as a function of year there
dur, dur_edges = np.histogram(df['Expiration Year'][region_mask],
                              weights=df['Difference_Days'][region_mask],
                              bins=10)
# like before with our histograms
dur_centers = [(dur_edges[i]+dur_edges[i+1])*0.5 for i in range(len(dur_edges)-1)]
# make histogram by hand, weighting by duration
duration_hist = bqplot.Bars(x=dur_centers, y=dur, 
                          scales={'x':x_scl, 'y':y_scl})
fig_dur = bqplot.Figure(marks = [duration_hist], axes = [ax_xcl, ax_ycl])
fig_dur

Figure(axes=[Axis(label='Year', scale=OrdinalScale()), Axis(label='Median days', orientation='vertical', scale…

In [20]:
mySelectedLabel = ipywidgets.Label()
def get_data_value2(change):
    i,j = change['owner'].selected[0]
    v = ndf[i,j] # grab data value
    mySelectedLabel.value = 'Data About days to get a License = ' + str(v) # set our label
    # note!! i & j are swapped here to machup with hist & selection
    ey = [df['Expiration Year'][j], df['Expiration Year'][j+1]]
    oiy = [df['Original Issue Year'][i],df['Original Issue Year'][i+1]]
    region_mask = ( (df['Original Issue Year'] >= oiy[0]) & (df['Original Issue Year']<=oiy[1]) &\
                (df['Expiration Year'] >= ey[0]) & (df['Expiration Year']<=ey[1]) )
    duration_scatt.x = ndf['date'][region_mask]
    duration_scatt.y = ndf['duration_seconds'][region_mask]
    #print(i,j)
    #print(longs,lats)
    #print(ufos['date'][region_mask])
# make sure we connect to heatmap     
heat_map.observe(get_data_value2, 'selected')


ipywidgets.VBox([mySelectedLabel, ipywidgets.HBox([fig,fig_dur])])
# note that when I select a deep purple place, my scatter plot is 
#  very laggy, this makes me think we should do this with a 
#  histogram/bar type plot

VBox(children=(Label(value=''), HBox(children=(Figure(axes=[ColorAxis(orientation='vertical', scale=ColorScale…

ValueError: Unsupported dtype object

ValueError: Unsupported dtype object